[theme]

# Primary accent for interactive elements
primaryColor = '#FF0046'

# Background color for the main content area
backgroundColor = '#050E1E'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#0C182C'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
